---
- name: Apache server
  apt: name=apache2

- name: PHP 5.x and extensions
  apt: name=php5,php5-curl,php5-pgsql,php5-xdebug

- name: php.ini customization
  copy: src=files/php-extra.ini dest=/etc/php5/{{item}}/conf.d/50-timezone.ini
  with_items:
    - apache2
    - cli

- name: run Apache process under the 'vagrant' user
  lineinfile: dest=/etc/apache2/envvars
    regexp='export {{ item }}'
    line='export {{ item }}=vagrant'
  with_items:
    - APACHE_RUN_USER
    - APACHE_RUN_GROUP
  notify:
    reload Apache
