---
- name: PHP 5.x and extensions
  apt: name={{ item }}
  with_items:
    - php5
    - php5-curl
    - php5-pgsql
    - php5-xdebug
    - php5-intl
  notify:
    reload Apache

- name: php.ini customization
  copy: src=php-extra.ini dest=/etc/php5/{{item}}/conf.d/90-extra.ini
  with_items:
    - apache2
    - cli
  notify:
    reload Apache

- name: run Apache process under the 'vagrant' user
  lineinfile: dest=/etc/apache2/envvars
    regexp='export {{ item }}'
    line='export {{ item }}=vagrant'
  with_items:
    - APACHE_RUN_USER
    - APACHE_RUN_GROUP
  notify:
    reload Apache
