---
- name: (purge HHVM)
  apt: name=hhvm state=absent

- name: PHP 5.x and extensions
  apt: name={{ item }}
  with_items:
    - php5-cli
    - php5-curl
    - php5-fpm
    - php5-pgsql
    - php5-xdebug
    - php5-intl
  notify:
    restart Apache

- name: php.ini customization
  copy: src=php-extra.ini dest=/etc/php5/{{item}}/conf.d/90-extra.ini
  with_items:
    - apache2
    - cli
  notify:
    restart Apache
