---
- name: PostgreSQL server and client
  apt: name=postgresql-9.6,libpq-dev,python-psycopg2

- name: PostgreSQL database user
  sudo_user: postgres
  postgresql_user: name={{ dbuser }} password={{ dbpassword }}

- name: PostgreSQL database init
  sudo_user: postgres
  postgresql_db: name={{ dbname }} owner={{ dbuser }}

# - name: PostgreSQL database grants
#   sudo_user: postgres
#   postgresql_privs: db=symfony role=vagrant objs=ALL_IN_SCHEMA priv=ALL
