---
- hosts: all
  sudo: yes
  vars:
    APPDIR: "/vagrant/{{ APPNAME }}"
    when: APPNAME is defined
    APPWEBROOT: "{{ APPDIR }}/web"
    when: APPNAME is defined
    APPCOMMONDIR: "/vagrant"

  pre_tasks:
    - name: check last APT update time
      shell: echo $(( $(date +%s) - $(stat -c %Y /var/lib/apt/periodic/update-success-stamp) ))
      register: apt_cache_age
    - name: update apt database
      apt: update_cache=yes
      when: (apt_cache_age.stdout|int) > 86400

  roles:
    - apache
    - postgresql
    - hhvm
    - symfony
    - { role: webapp, when: APPNAME is defined }
    - vagrantbox
