---
- hosts: all
  sudo: yes
  pre_tasks:
    - name: update apt database
      apt: update_cache=yes
  roles:
    - webserver
    - postgresql
    - symfony
    - { role: webapp, when: APPNAME is defined }
