---
- hosts: all
  become: yes
  vars:
    APPDIR: "/vagrant"
    APPWEBROOT: "{{ APPDIR }}/web"
    APPCOMMONDIR: "/opt"
    APPUSER: "vagrant"

  pre_tasks:
    - name: check last APT update time
      apt: update_cache=yes cache_valid_time=86400

    - name: add non free repositories
      apt_repository: repo={{ item }} state=present
      with_items:
        - deb http://ftp.us.debian.org/debian/ jessie main contrib non-free
        - deb http://security.debian.org/ jessie/updates main contrib non-free

  roles:
    - apache
    - "{{ dbtype }}"
    # - hhvm
    - php
    - git
    - symfony
    - webapp
    - webapp-container
    - vagrantbox
