---
- debug: msg={{ APPDIR }}
- name: initialize application
  command: creates={{ APPDIR }}/
    /vagrant/composer.phar create-project --no-interaction --quiet symfony/framework-standard-edition {{ APPDIR }}
  sudo_user: vagrant

- name: default gitignore
  copy: src=Symfony.gitignore dest={{ APPDIR }}/.gitignore force=no

- name: add container - Apache VirtualHost
  template: src=apache2.vhost.j2 dest=/etc/apache2/sites-available/{{ APPNAME }}.conf
  notify:
    restart Apache

- name: enable container - Apache VirtualHost
  command: creates=/etc/apache2/sites-enabled/{{ APPNAME }}.conf
    a2ensite {{ APPNAME }}
  notify:
    restart Apache
