---
- name: initialize application
  command: chdir=/vagrant creates=/vagrant/{{ APPNAME }}/
    symfony new --no-interaction --quiet {{ APPNAME }}

- name: default gitignore
  copy: src=files/Symfony.gitignore dest=/vagrant/{{ APPNAME }}/.gitignore force=no

- name: add Apache VirtualHost
  template: src=files/{{ APPNAME }}.vhost dest=/etc/apache2/sites-available/{{ APPNAME }}.conf
  notify:
    reload Apache

- name: disable Apache default site
  command: removes=/etc/apache2/sites-enabled/000-default.conf
    a2dissite 000-default
  notify:
    reload Apache

- name: enable Apache VirtualHost
  command: creates=/etc/apache2/sites-enabled/{{ APPNAME }}.conf
    a2ensite {{ APPNAME }}
  notify:
    reload Apache
