---
- name: setup PHP Composer
  shell: creates=composer.phar chdir=/vagrant
    curl -sS https://getcomposer.org/installer | php

- name: setup framework
  shell: creates=symfony.phar chdir=/vagrant
    curl -LsS http://symfony.com/installer > symfony.phar

- name: make framework installer executable
  file: path=/vagrant/symfony.phar mode='ugo+x'

- name: symlink .phar files
  file: src=/vagrant/{{item}}.phar dest=/usr/local/bin/{{item}} state=link
  with_items:
    - composer
    - symfony
